# Schema for the configuration files of the CivicTheme theme.

civictheme.settings:
  type: theme_settings
  label: 'CivicTheme settings'
  mapping:
    components:
      type: mapping
      label: 'Components settings'
      mapping:
        logo:
          type: mapping
          label: 'Logo settings'
          mapping:
            primary:
              type: mapping
              label: Primary
              mapping:
                light:
                  type: mapping
                  label: Light
                  mapping:
                    desktop:
                      label: Desktop
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
                    mobile:
                      label: Mobile
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
                dark:
                  type: mapping
                  label: Dark
                  mapping:
                    desktop:
                      label: Desktop
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
                    mobile:
                      label: Mobile
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
            secondary:
              type: mapping
              label: Primary
              mapping:
                light:
                  type: mapping
                  label: Light
                  mapping:
                    desktop:
                      label: Desktop
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
                    mobile:
                      label: Mobile
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
                dark:
                  type: mapping
                  label: Dark
                  mapping:
                    desktop:
                      label: Desktop
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
                    mobile:
                      label: Mobile
                      type: mapping
                      mapping:
                        path:
                          label: Path
                          type: string
        header:
          type: mapping
          label: 'Header settings'
          mapping:
            theme:
              label: Theme
              type: string
            logo_type:
              label: 'Logo type'
              type: string
        navigation:
          type: mapping
          label: 'Navigation settings'
          mapping:
            primary_navigation:
              type: mapping
              label: 'Primary navigation settings'
              mapping:
                dropdown:
                  label: 'Dropdown type'
                  type: string
                dropdown_columns:
                  label: 'Number of columns in dropdown'
                  type: integer
                dropdown_columns_fill:
                  label: 'Fill width of the last dropdown row'
                  type: boolean
                is_animated:
                  label: 'Animate transition'
                  type: boolean
            secondary_navigation:
              type: mapping
              label: 'Secondary navigation settings'
              mapping:
                dropdown:
                  label: 'Dropdown type'
                  type: string
                dropdown_columns:
                  label: 'Number of columns in dropdown'
                  type: integer
                dropdown_columns_fill:
                  label: 'Fill width of the last dropdown row'
                  type: boolean
                is_animated:
                  label: 'Animate transition'
                  type: boolean
        footer:
          type: mapping
          label: 'Footer settings'
          mapping:
            theme:
              label: Theme
              type: string
            logo_type:
              label: 'Logo type'
              type: string
            background_image:
              label: 'Footer background image'
              type: mapping
              mapping:
                path:
                  label: 'Footer background image path'
                  type: string
        link:
          type: mapping
          label: 'Link settings'
          mapping:
            new_window:
              label: 'Open all links in the new window'
              type: boolean
            external_new_window:
              label: 'Open external links in the new window'
              type: boolean
            external_override_domains:
              label: 'List of override domains for external links'
              type: sequence
              sequence:
                type: string
        skip_link:
          type: mapping
          label: 'Skip Link settings'
          mapping:
            theme:
              label: Theme
              type: string
        event_card:
          type: mapping
          label: 'Event card settings'
          mapping:
            summary_length:
              label: 'Summary length'
              type: integer
        navigation_card:
          type: mapping
          label: 'Navigation card settings'
          mapping:
            summary_length:
              label: 'Summary length'
              type: integer
        promo_card:
          type: mapping
          label: 'Promo card settings'
          mapping:
            summary_length:
              label: 'Summary length'
              type: integer
        publication_card:
          type: mapping
          label: 'Publication card settings'
          mapping:
            summary_length:
              label: 'Summary length'
              type: integer
    colors:
      type: mapping
      label: Colors
      mapping:
        use_color_selector:
          label: 'Use Color Selector'
          type: boolean
        use_brand_colors:
          label: 'Use Brand colors'
          type: boolean
        brand:
          type: mapping
          label: 'Brand colors'
          mapping:
            light:
              type: mapping
              label: Light
              mapping:
                brand1:
                  label: Brand1
                  type: string
                brand2:
                  label: Brand2
                  type: string
                brand3:
                  label: Brand3
                  type: string
            dark:
              type: mapping
              label: Dark
              mapping:
                brand1:
                  label: Brand1
                  type: string
                brand2:
                  label: Brand2
                  type: string
                brand3:
                  label: Brand3
                  type: string
        palette:
          type: mapping
          label: 'Palette colors'
          mapping:
            theme:
              type: mapping
              label: Light
              mapping:
                heading:
                  label: Heading
                  type: string
                body:
                  label: Body
                  type: string
                background_light:
                  label: 'Background light'
                  type: string
                background:
                  label: Background
                  type: string
                background_dark:
                  label: 'Background dark'
                  type: string
                border_light:
                  label: 'Border light'
                  type: string
                border:
                  label: Border
                  type: string
                border_dark:
                  label: 'Border dark'
                  type: string
                interaction_text:
                  label: 'Interaction text'
                  type: string
                interaction_background:
                  label: 'Interaction background'
                  type: string
                interaction_hover_text:
                  label: 'Interaction hover text'
                  type: string
                interaction_hover_background:
                  label: 'Interaction hover background'
                  type: string
                interaction_focus:
                  label: 'Interaction focus'
                  type: string
                highlight:
                  label: Highlight
                  type: string
                information:
                  label: Information
                  type: string
                warning:
                  label: Warning
                  type: string
                error:
                  label: Error
                  type: string
                success:
                  label: Success
                  type: string
            dark:
              type: mapping
              label: Dark
              mapping:
                heading:
                  label: Heading
                  type: string
                body:
                  label: Body
                  type: string
                background_light:
                  label: 'Background light'
                  type: string
                background:
                  label: Background
                  type: string
                background_dark:
                  label: 'Background dark'
                  type: string
                border_light:
                  label: 'Border light'
                  type: string
                border:
                  label: Border
                  type: string
                border_dark:
                  label: 'Border dark'
                  type: string
                interaction_text:
                  label: 'Interaction text'
                  type: string
                interaction_background:
                  label: 'Interaction background'
                  type: string
                interaction_hover_text:
                  label: 'Interaction hover text'
                  type: string
                interaction_hover_background:
                  label: 'Interaction hover background'
                  type: string
                interaction_focus:
                  label: 'Interaction focus'
                  type: string
                highlight:
                  label: Highlight
                  type: string
                information:
                  label: Information
                  type: string
                warning:
                  label: Warning
                  type: string
                error:
                  label: Error
                  type: string
                success:
                  label: Success
                  type: string
    migration:
      type: mapping
      label: Migration
      mapping:
        expose_metadata:
          label: 'Expose migration metadata'
          type: boolean
